services:

  core:
    image: karankumar9955/core:latest
    container_name: core
    pull_policy: always
    restart: unless-stopped
    env_file:
      - core.env
    expose:
      - "9090"
    networks:
      - app

  mail:
    image: karankumar9955/mail:latest
    container_name: mail
    pull_policy: always
    restart: unless-stopped
    env_file:
      - mail.env
    networks:
      - app

  admin:
    image: karankumar9955/admin:latest
    container_name: admin
    pull_policy: always
    restart: unless-stopped
    env_file:
      - admin.env
    expose:
      - "8000"
    networks:
      - app

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app

networks:
  app:

volumes:
  caddy_data:
  caddy_config: