spring:

  cloud:
    openfeign:
      client:
        config:
          audioProcessingApi:
            # retryer: feign.Retryer.Default
            # max-attempts: 3
            # period: 100
            # max-period: 1000

  config:
    import: optional:file:.env[.properties]

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:user}
    password: ${MAIL_PASSWORD:pass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: ${APPLICATION_NAME:melody}
    api-key: ${APPLICATION_API_KEY:default_api_key}
    admin:
      name: ${ADMIN_NAME:default_admin_name}
      email: ${ADMIN_EMAIL:admin@melody.com}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/melody}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      mailqueue: ${REDIS_MAIL_QUEUE}
      audioprocessingqueue: ${REDIS_AUDIO_PROCESSING_QUEUE}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:true}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true

jwt:
  secret: ${JWT_SECRET:default_jwt_secret_key_which_should_be_long_enough_to_work_properly}
server:
  port: ${PORT:8080}

algolia:
  app-id: ${ALGOLIA_APP_ID:default_algolia_app_id}
  api-key: ${ALGOLIA_API_KEY:default_algolia_api_key}
  index-name: ${ALGOLIA_INDEX_NAME:default_algolia_index_name}

recombee:
  database-id: ${RECOMBEE_DATABASE_ID:default_recombee_db_id}
  secret-token: ${RECOMBEE_DATABASE_SECRET:default_recombee_token}
  region: ${RECOMBEE_DATABASE_REGION:EU_WEST}

aws:
  accesskeyid: ${AWS_ACCESS_KEY_ID:default_access_key}
  secretkey: ${AWS_SECRET_ACCESS_KEY:default_secret_key}
  region: ${AWS_REGION:ap-south-1}
  endpoint: ${AWS_ENDPOINT:}

s3:
  temp-bucket: ${S3_TEMP_BUCKET:melody-temp}
  song-bucket: ${S3_SONG_BUCKET:melody-songs}
  temp-url-validity-min: 30

audio-processing:
    api:
      key: ${AUDIO_PROCESSING_API_KEY:default_audio_processing_key}
      url: ${AUDIO_PROCESSING_URL:http://localhost:8000}

imagekit:
  public-key: ${IMAGEKIT_PUBLIC_KEY:default_public_key}
  private-key: ${IMAGEKIT_PRIVATE_KEY:default_private_key}
  url-endpoint: ${IMAGEKIT_URL_ENDPOINT:https://ik.imagekit.io/default}

