# Generated by Django 6.1.1 on 2026-10-02 02:43

# pyrefly: ignore [missing-import]
import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image_key', models.CharField(blank=True, db_column='cover_image_key', max_length=255, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'artists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeleteJob',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_column='entity_type', max_length=255)),
                ('entity_id', models.CharField(db_column='entity_id', max_length=255)),
                ('entity_title', models.CharField(blank=True, db_column='entity_title', max_length=255, null=True)),
                ('song_key', models.CharField(blank=True, db_column='song_key', max_length=255, null=True)),
                ('image_key', models.CharField(blank=True, db_column='image_key', max_length=255, null=True)),
                ('cover_image_key', models.CharField(blank=True, db_column='cover_image_key', max_length=255, null=True)),
                ('video_key', models.CharField(blank=True, db_column='video_key', max_length=255, null=True)),
                ('full_video_key', models.CharField(blank=True, db_column='full_video_key', max_length=255, null=True)),
                ('status', models.CharField(default='PENDING', max_length=255)),
                ('current_stage', models.CharField(db_column='current_stage', default='QUEUED', max_length=255)),
                ('attempt_count', models.IntegerField(db_column='attempt_count', default=0)),
                ('max_attempts', models.IntegerField(db_column='max_attempts', default=3)),
                ('failure_reason', models.TextField(blank=True, db_column='failure_reason', null=True)),
                ('started_at', models.DateTimeField(blank=True, db_column='started_at', null=True)),
                ('search_deleted_at', models.DateTimeField(blank=True, db_column='search_deleted_at', null=True)),
                ('recommendation_deleted_at', models.DateTimeField(blank=True, db_column='recommendation_deleted_at', null=True)),
                ('imagekit_deleted_at', models.DateTimeField(blank=True, db_column='imagekit_deleted_at', null=True)),
                ('s3_deleted_at', models.DateTimeField(blank=True, db_column='s3_deleted_at', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', null=True)),
                ('failed_at', models.DateTimeField(blank=True, db_column='failed_at', null=True)),
                ('search_duration_ms', models.BigIntegerField(blank=True, db_column='search_duration_ms', null=True)),
                ('recommendation_duration_ms', models.BigIntegerField(blank=True, db_column='recommendation_duration_ms', null=True)),
                ('imagekit_duration_ms', models.BigIntegerField(blank=True, db_column='imagekit_duration_ms', null=True)),
                ('s3_duration_ms', models.BigIntegerField(blank=True, db_column='s3_duration_ms', null=True)),
                ('finalize_duration_ms', models.BigIntegerField(blank=True, db_column='finalize_duration_ms', null=True)),
                ('total_duration_ms', models.BigIntegerField(blank=True, db_column='total_duration_ms', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'delete_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(db_column='artist_name', max_length=255)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('temp_song_key', models.CharField(blank=True, db_column='temp_song_key', max_length=255, null=True)),
                ('temp_video_key', models.CharField(blank=True, db_column='temp_video_key', max_length=255, null=True)),
                ('song_key', models.CharField(blank=True, db_column='song_key', max_length=255, null=True)),
                ('full_video_key', models.CharField(blank=True, db_column='full_video_key', max_length=255, null=True)),
                ('image_key', models.CharField(db_column='image_key', max_length=255)),
                ('video_key', models.CharField(blank=True, db_column='video_key', max_length=255, null=True)),
                ('clip_start_sec', models.IntegerField(blank=True, db_column='clip_start_sec', null=True)),
                ('clip_end_sec', models.IntegerField(blank=True, db_column='clip_end_sec', null=True)),
                ('preview_start_time', models.IntegerField(blank=True, db_column='preview_start_time', null=True)),
                ('preview_end_time', models.IntegerField(blank=True, db_column='preview_end_time', null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('lrclib_id', models.CharField(blank=True, db_column='lrclib_id', max_length=255, null=True)),
                ('song_id', models.CharField(db_column='song_id', max_length=255)),
                ('transcoding_id', models.CharField(blank=True, db_column='transcoding_id', max_length=255, null=True)),
                ('transcoding_attempt', models.IntegerField(db_column='transcoding_attempt', default=0)),
                ('transcoded', models.BooleanField(default=False)),
                ('saved_in_search', models.BooleanField(db_column='saved_in_search', default=False)),
                ('saved_in_recommendation', models.BooleanField(db_column='saved_in_recommendation', default=False)),
                ('is_video_reprocess', models.BooleanField(db_column='is_video_reprocess', default=False)),
                ('is_audio_reprocess', models.BooleanField(db_column='is_audio_reprocess', default=False)),
                ('status', models.CharField(default='QUEUED', max_length=255)),
                ('current_stage', models.CharField(db_column='current_stage', default='QUEUED', max_length=255)),
                ('transcoding_started_at', models.DateTimeField(blank=True, db_column='transcoding_started_at', null=True)),
                ('transcoded_at', models.DateTimeField(blank=True, db_column='transcoded_at', null=True)),
                ('recommendation_saved_at', models.DateTimeField(blank=True, db_column='recommendation_saved_at', null=True)),
                ('search_saved_at', models.DateTimeField(blank=True, db_column='search_saved_at', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', null=True)),
                ('failed_at', models.DateTimeField(blank=True, db_column='failed_at', null=True)),
                ('failure_reason', models.TextField(blank=True, db_column='failure_reason', null=True)),
                ('transcoding_duration_ms', models.BigIntegerField(blank=True, db_column='transcoding_duration_ms', null=True)),
                ('recommendation_duration_ms', models.BigIntegerField(blank=True, db_column='recommendation_duration_ms', null=True)),
                ('search_duration_ms', models.BigIntegerField(blank=True, db_column='search_duration_ms', null=True)),
                ('finalize_duration_ms', models.BigIntegerField(blank=True, db_column='finalize_duration_ms', null=True)),
                ('total_duration_ms', models.BigIntegerField(blank=True, db_column='total_duration_ms', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaginationMetadata',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(db_column='entity_name', max_length=255, unique=True)),
                ('total_count', models.BigIntegerField(db_column='total_count', default=0)),
                ('active_count', models.BigIntegerField(db_column='active_count', default=0)),
                ('blocked_count', models.BigIntegerField(db_column='blocked_count', default=0)),
                ('deleted_count', models.BigIntegerField(db_column='deleted_count', default=0)),
            ],
            options={
                'db_table': 'pagination_metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image_key', models.CharField(db_column='cover_image_key', max_length=255)),
                ('video_key', models.CharField(blank=True, db_column='video_key', max_length=255, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'playlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'playlist_songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(db_column='artist_name', max_length=255)),
                ('duration', models.IntegerField()),
                ('song_key', models.CharField(db_column='song_key', max_length=255)),
                ('image_key', models.CharField(db_column='image_key', max_length=255)),
                ('video_key', models.CharField(blank=True, db_column='video_key', max_length=255, null=True)),
                ('full_video_key', models.CharField(blank=True, db_column='full_video_key', max_length=255, null=True)),
                ('preview_start_time', models.IntegerField(blank=True, db_column='preview_start_time', null=True)),
                ('preview_end_time', models.IntegerField(blank=True, db_column='preview_end_time', null=True)),
                ('is_featured', models.BooleanField(db_column='is_featured', default=False)),
                ('language', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('lrclib_id', models.CharField(db_column='lrclib_id', max_length=255)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('job_id', models.CharField(db_column='job_id', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, db_column='user_name', max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(default='USER', max_length=255)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('role', models.CharField(default='ADMIN', max_length=255)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'admin_users',
                'managed': True,
            },
        ),
    ]
