spring:

  cloud:
    openfeign:
      client:
        config:
          audioProcessingApi:
            # retryer: feign.Retryer.Default
            # max-attempts: 3
            # period: 100
            # max-period: 1000

  config:
    import: optional:file:.env[.properties]

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: ${APPLICATION_NAME}
    api-key: ${APPLICATION_API_KEY}
    admin:
      id: ${ADMIN_ID}
      name: ${ADMIN_NAME}
      email: ${ADMIN_EMAIL}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
server:
  port: ${PORT}

algolia:
  app-id: ${ALGOLIA_APP_ID}
  api-key: ${ALGOLIA_API_KEY}
  index-name: ${ALGOLIA_INDEX_NAME}

recombee:
  database-id: ${RECOMBEE_DATBASE_ID}
  secret-token: ${RECOMBEE_DATBASE_SECRET}
  region: ${RECOMBEE_DATBASE_REGION}

audio-processing:
    api:
      key: ${AUDIO_PROCESSING_API_KEY}
      url: ${AUDIO_PROCESSING_URL}
